# Generated by Django 5.1.4 on 2025-02-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
