# Generated by Django 5.1.4 on 2025-02-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_problem_problem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeday",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenge.challengegroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="challengeday",
            unique_together={("group", "date")},
        ),
        migrations.RemoveField(
            model_name="challengeday",
            name="challenge",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
    ]
